name: Desarrollo

permissions:
  id-token: write
  contents: read
concurrency: dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Build:
    name: Build
    runs-on:
    - ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

  Deploy:
    name: Deploy
    runs-on:
    - ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: "Información"
      run: |
        cat INFO.md >> "$GITHUB_STEP_SUMMARY" || echo "No hay archivo INFO.md"

  LoadTest:
    name: LoadTest
    runs-on:
    - ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: "Load test"
      run: |
        docker run --rm ddosify/ddosify ddosify -t https://app.servdown.com
        
    
